name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Add sbt repository and install sbt
      run: |
        echo "Adding sbt repository..."
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        curl -fsSL https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823 | sudo gpg --dearmor -o /usr/share/keyrings/sbt-archive-keyring.gpg
        sudo apt-get update
        sudo apt-get install -y sbt
    - name: Run tests
      run: sbt test
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@v2
